### ISSUE TITLE
`sudo brew services restart` not working when service is stopped

### ISSUE THREAD

**Issue by adamwathan** [Homebrew/homebrew-services#102] opened 2017-02-03 01:28 UTC
Having a weird issue lately where services that need to run as root can't be "restarted" if they are stopped; only if they are running.

It shows up as a permissions issue, then claims the services has started, but it hasn't:

![image](https://cloud.githubusercontent.com/assets/4323180/22575849/56d8957e-e986-11e6-9cfd-4838d7ff84ef.png)

`sudo brew services start nginx` will start nginx as root from stopped just fine, its just `restart` that fails:

![image](https://cloud.githubusercontent.com/assets/4323180/22575860/6851f638-e986-11e6-9e8a-8551cd73e1d7.png)

Have a bunch of other folks using a project I help maintain that leverages homebrew running into similar issues:

https://github.com/laravel/valet/issues/305
https://github.com/laravel/valet/issues/298#issuecomment-274799696

Is this actually a permissions issue like reported? Homebrew seems to start services as root just fine even if root doesn't own the plist, just restart fails.

Thanks!

**Comment by adamwathan** [comment] 2017-02-03 01:32
Maybe related, but what's the meaning behind the yellow vs. green for the "started" text, and why would `sudo brew services list` show MySQL as stopped, but `brew services list` show it as running?

![image](https://cloud.githubusercontent.com/assets/4323180/22575937/c72835fa-e986-11e6-9156-9b48326accda.png)


The plist locations are sort of interesting as well, the ones listed for the root services don't match the path that Homebrew complains has incorrect permissions.

**Comment by MikeMcQuaid** [comment] 2017-02-03 15:19
> Maybe related, but what's the meaning behind the yellow vs. green for the "started" text

Basically: we've asked it to start but `launchd` doesn't know if it's actually running or not: https://github.com/Homebrew/homebrew-services/blob/463cbe5c064d5e38e18dd90da6104d60b7fb2128/cmd/brew-services.rb#L179-L186. This may point towards a fork and detach model where the original process is no longer running.

> Is this actually a permissions issue like reported? Homebrew seems to start services as root just fine even if root doesn't own the plist, just restart fails.

I'm pretty sure this message is coming from `launchctl` itself rather than `brew services` so you may want to try and see if you can reproduce it just with that. Closing this until then because I'm not sure this is actionable for us as-is. Sorry; still happy to keep chatting about this here.

**Comment by adamwathan** [comment] 2017-02-03 15:26
Sure, so I guess my main question is what is different about:

```
sudo brew services stop nginx
sudo brew services start nginx
```

vs. this:

```
sudo brew services restart nginx
```

The first always works reliably regardless of the state the service is in, but the second fails if the service is not running.

Any recommendations on things to look for or read about to try and understand the issue better?

**Comment by MikeMcQuaid** [comment] 2017-02-03 15:30
You can check the code to see the exact differences but my guess would be a timing issue. Does `sudo brew services stop nginx; sudo brew services start nginx` (i.e. with no human delay) consistently behave differently?

**Comment by PeterDKC** [comment] 2017-02-03 19:11
This is due to the .plist file physically disappearing from either the LaunchAgenst or LaunchDaemons folder when the service isn't up. It only places it in one or the other when the brew services command runs. So the file stat says "Path had bad ownership" because it can't find it.

```
pdemarco-mn1:~ pdemarco$ sudo brew services list
Name    Status  User     Plist
dnsmasq started root     /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
httpd24 stopped
mysql   started pdemarco /Users/pdemarco/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx   started root     /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php70   stopped
pdemarco-mn1:~ pdemarco$ ls /Library/LaunchDaemons/ | grep nginx
homebrew.mxcl.nginx.plist
pdemarco-mn1:~ pdemarco$ sudo brew services stop nginx
Stopping `nginx`... (might take a while)
==> Successfully stopped `nginx` (label: homebrew.mxcl.nginx)
pdemarco-mn1:~ pdemarco$ ls /Library/LaunchDaemons/ | grep nginx
pdemarco-mn1:~ pdemarco$ sudo brew services restart nginx
/usr/local/Cellar/nginx/1.10.3/homebrew.mxcl.nginx.plist: Path had bad ownership/permissions
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)
pdemarco-mn1:~ pdemarco$
```

**Comment by adamwathan** [comment] 2017-02-12 01:00
@MikeMcQuaid Sorry for not replying sooner, indeed `sudo brew services stop nginx; sudo brew services start nginx` always works and `sudo brew services restart nginx` never works:

![image](https://cloud.githubusercontent.com/assets/4323180/22858721/6defa23e-f093-11e6-91dd-02ffd2b638d5.png)

**Closed** 2017-02-23 11:23 UTC

**Comment by adamwathan** [comment] 2017-02-23 12:51
🙌🏻 Thanks Mike!

**Comment by MikeMcQuaid** [comment] 2017-02-23 14:37
@adamwathan My pleasure. Thanks for the great report and persistency in the face of my initial (wrong) assumptions 😆

**Comment by abetsagaral** [comment] 2017-09-11 01:24
mysql.server start

**Comment by JCount** [comment] 2017-09-11 06:29
@adamwathan Please to not comment on long closed issues. If you have a problem, open a new issue rather than comment on ancient ones.
