### ISSUE TITLE
How do we see the details if the service shows the state "error"

### ISSUE THREAD

**Issue by lacivert** [Homebrew/homebrew-services#92] opened 2016-12-27 07:15 UTC
I installed mysql via brew and I saw that it was working yesterday by list command;

`brew services list`

But today I see that mysql service has the "error" state even though it looks like it works without a problem.

Now how can we see why brew list says there is an error and how do we see the details of this "error" state?

**Comment by lacivert** [comment] 2016-12-27 07:16
```
$ brew services list
Name           Status  User  Plist
docker-machine stopped       
mysql          error   yasin /Users/yasin/Library/LaunchAgents/homebrew.mxcl.mysql.plist
postgresql     stopped 
```

**Comment by ilovezfs** [comment] 2016-12-27 07:52
You can enable logging of stdout to a file and stderr to a file in the plist with the keys StandardOutPath and StandardErrorPath, which should throw some light on what's happening.

**Comment by lacivert** [comment] 2016-12-28 11:55
Thanks @ilovezfs. Sorry about that but I don't know what these are all about on your comment. How can I do that exactly (or how should I search on Google what these all means shortly)?

**Comment by MikeMcQuaid** [comment] 2016-12-29 12:29
If a service shows "error" that means that launchd has detected an error since the process was started. It may be still running on your machine, though, but it just means that `launchd` has detected an issue. If it's working fine you can ignore it.

CC @antstorm for additional thoughts/corrections and how we can perhaps adjust this to improve the usability.

**Comment by antstorm** [comment] 2016-12-29 12:37
@lacivert so `error` status means one of two things — either `launchd` doesn't have PID of the process or the exit code was non-zero. Both mean that there's something wrong with the service and `launchd` won't be able to handle it properly.

Can you please copy the output of `launchctl list | grep mysql` and `ps aux | grep [m]ysql`?

**Comment by lacivert** [comment] 2016-12-29 14:31
@antstorm, un(!)fortunately now mysql looks "started" well without error state, but I'll try to response you if I get the same issue.

**Comment by antstorm** [comment] 2016-12-29 16:44
@lacivert oh, I see. Well in case that happens it's worth looking at `launchctl list` to see what exactly is going on.

**Comment by MikeMcQuaid** [comment] 2016-12-30 18:45
Closing this as we've got instructions on what to do here. 

@antstorm Thoughts about how to expose or document this better? Put an explanation in the README? If so, is that something you could open a PR for? Thanks!

**Comment by antstorm** [comment] 2016-12-31 11:54
@MikeMcQuaid yeah, I'll open a PR. Apart from README we can use the `unknown` status (which is slightly more gentle than `error`) when the exit code was `0`, but there's a `pid` missing.

**Comment by MikeMcQuaid** [comment] 2016-12-31 17:12
> @MikeMcQuaid yeah, I'll open a PR. Apart from README we can use the unknown status (which is slightly more gentle than error) when the exit code was 0, but there's a pid missing.

@antstorm Thanks! I reckon a missing pid should also probably just be `started`.

**Comment by antstorm** [comment] 2017-01-02 12:11
@MikeMcQuaid not really and a very popular use case here is `redis`. It has `daemonize yes` listed in default settings, which somehow conflicts with `launchd` resulting in it **not** running and:

```
$ launchctl list | grep redis
-	0	homebrew.mxcl.redis
```

This also might try to unsuccessfully restart the service every 10 seconds depending on the settings in `plist`.

**Comment by MikeMcQuaid** [comment] 2017-01-02 18:09
@antstorm Thanks for fixing up `redis`. My view is we should save non-`started` for cases where we 100% know it's failed. That means we provide an improvement on the existing `brew services` interface without causing confusion when it's working fine (and just the plist has been misconfigured). I'd agree with making `unknown` be shown if `HOMEBREW_DEVELOPER` is set in the environment, though as those are the folks who might know enough to fix it.

**Comment by antstorm** [comment] 2017-01-02 19:56
@MikeMcQuaid I think both missing pid and non-zero exit code are good indicators that there's something wrong with the service. `error` might be a bit too harsh, but `started` is as confusing, because probably nothing's running.

I wonder if exposing pid would make a difference in reporting what's happening with the service. It's not for me to decide, but it would be really great to have all the info needed to figure out what's happening in `brew services list`, without having to `ps aux`, `launchctl list` and so on…

**Comment by MikeMcQuaid** [comment] 2017-01-02 20:04
> I think both missing pid and non-zero exit code are good indicators that there's something wrong with the service. error might be a bit too harsh, but started is as confusing, because probably nothing's running.

Sure. I think the difference is that one indicates a failure in starting and one may just indicate the Homebrew plist has been misconfigured. Given the latter we don't have 100% certainty that the service isn't running I think we should err on the side of maintaining the previous interface for non-Homebrew developers.

> I wonder if exposing pid would make a difference in reporting what's happening with the service. It's not for me to decide, but it would be really great to have all the info needed to figure out what's happening in brew services list, without having to ps aux, launchctl list and so on…

More subcommands that wrap `launchctl` would certainly be useful 👍

**Comment by antstorm** [comment] 2017-01-02 21:03
@MikeMcQuaid 

> Sure. I think the difference is that one indicates a failure in starting and one may just indicate the Homebrew plist has been misconfigured. Given the latter we don't have 100% certainty that the service isn't running I think we should err on the side of maintaining the previous interface for non-Homebrew developers.

Not really, if the service simply decided to stop executing (shouldn't normally happen, but still very possible). Missing pid also means that stopping the service with `brew services stop SERVICE` won't actually do anything apart from removing the `plist`. What I'm getting at is that I'd rather know there's something wrong with the services than have to manually check it just to find out it's not actually running.

But then again, it's only my opinion… 😄

**Comment by MikeMcQuaid** [comment] 2017-01-02 21:24
> But then again, it's only my opinion… 😄 Perfectly happy to agree to disagree on this one and do whatever you think is better for the project and it's users.

Yeh, I think having it be an optional flag for now would be best 👍

**Comment by lacivert** [comment] 2017-01-03 08:47
my 5 pennies; it the state is "unknown" for brew, could it be better to see "unknown" when we command "services list"?

**Comment by uicosp** [comment] 2017-01-09 09:39
I had the same issue today.
after updated something (brew itself and the formula), my `dnsmasq` and `nginx` show error status, thought everything works well.

```
⋊> ~ brew services list                                                 16:57:59
Name    Status  User Plist
dnsmasq error root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
nginx   error root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
```

I run `
I debug as @ilovezfs said, but nothing in stdout.log and stderr.log .

Then I read the introduction on [A launchd Tutorial](http://www.launchd.info), and learned that there are several locations to define the job (.plist file) .  And

>launchd differentiates between agents and daemons. The main difference is that an agent is run on behalf of the logged in user while a daemon runs on behalf of the root user or any user you specify with the UserName key.

So I checked those locations, and find extra **dnsmasq** and **nginx** .plist files in `~/Library/LaunchAgents`.

So the problem is dnsmasq and nginx .plist files in `/Library/LaunchDaemons` has been loaded and started successfully when system(root) booted. Then load the files on behalf of current user in `~/Library/LaunchAgents` and try to start them again, since they started already, a not zero exit code return, this why we will see error status when run `brew services list`. 

run `sudo launchctl list | grep nginx`, I got this:

```
⋊> ~ sudo launchctl list | grep nginx                                   17:33:09
52	0	homebrew.mxcl.nginx
```

while run `launchctl list | grep nginx`:

```
⋊> ~ launchctl list | grep nginx                                   17:33:39
-	2	homebrew.mxcl.nginx
```

*How to fix*
Simply delete the extra files in `~/Library/LaunchAgents`, and restart your computer.
You will see the status is started now!

**Comment by antstorm** [comment] 2017-01-09 09:56
@uicosp I was able to replicate that behaviour by running a service (`nginx`) as a root and then as other user — it did fail to start a service the second time, while `plist` file was created anyways and thus showing the error.

I wonder if `brew services` should prevent from starting a service if it's already running by a different user…

**Comment by MikeMcQuaid** [comment] 2017-01-09 13:30
> I wonder if brew services should prevent from starting a service if it's already running by a different user…

@antstorm If it's possible to query that as a non-root user: it seems like a good idea.

**Comment by antstorm** [comment] 2017-01-09 13:57
@MikeMcQuaid should be possible, because we already do that to show services started as root. That would only rely on the `plist` file's presence though, but still might be worth implementing. WDYT?

**Comment by MikeMcQuaid** [comment] 2017-01-09 14:06
@antstorm I agree it's worth implementing. Want to give it a shot?

**Comment by antstorm** [comment] 2017-01-09 14:52
@MikeMcQuaid yeah, absolutely

**Comment by MikeMcQuaid** [comment] 2017-01-11 21:18
Going to close this because I consider it improved in a few ways.

**Closed by MikeMcQuaid** 2017-01-11 21:18 UTC
